//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kutuphane_otomasyonu
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class kutuphaneotomasyonEntities : DbContext
    {
        public kutuphaneotomasyonEntities()
            : base("name=kutuphaneotomasyonEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<personeller> personeller { get; set; }
        public virtual DbSet<Tbl_Personeller> Tbl_Personeller { get; set; }
        public virtual DbSet<Tbl_Uyeler> Tbl_Uyeler { get; set; }
        public virtual DbSet<Tbl_Kitaplar> Tbl_Kitaplar { get; set; }
        public virtual DbSet<Tbl_Odunc> Tbl_Odunc { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
