//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kutuphane_otomasyonu
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Personeller
    {
        public int person_id { get; set; }
        public string person_ad { get; set; }
        public string person_soyad { get; set; }
        public string person_tel { get; set; }
        public string person_mail { get; set; }
        public string person_tc { get; set; }
        public string person_sifre { get; set; }
    }
}
