//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kutuphane_otomasyonu
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Kitaplar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Kitaplar()
        {
            this.Tbl_Odunc = new HashSet<Tbl_Odunc>();
        }
    
        public int kaynak_id { get; set; }
        public string kaynak_ad { get; set; }
        public string kaynak_yazar { get; set; }
        public string kaynak_isbn { get; set; }
        public string kaynak_tur { get; set; }
        public string kaynak_dil { get; set; }
        public Nullable<int> kaynak_okumaSayisi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Odunc> Tbl_Odunc { get; set; }
    }
}
