//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kutuphane_otomasyonu
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Odunc
    {
        public int odunc_id { get; set; }
        public Nullable<int> kitap_id { get; set; }
        public Nullable<int> kullanici_id { get; set; }
        public Nullable<System.DateTime> alis_tarih { get; set; }
        public Nullable<System.DateTime> veris_tarih { get; set; }
        public Nullable<bool> durum { get; set; }
    
        public virtual Tbl_Kitaplar Tbl_Kitaplar { get; set; }
        public virtual Tbl_Uyeler Tbl_Uyeler { get; set; }
    }
}
